# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cd383b0fb4b481e0a7bf2fc202e1f9c518467719c648323af3f06d20ae132f0a1661b3668ff67543ac1675b36a941d775021572ee184521f7cffc24ccebfce8

test:
  secret_key_base: ff8eda4a4174d29a22892bf5c68ac6bff2b508c65fe6939ac906fd11dddf42912a16baeb2f4dc00f370caad7ebab5d3f6a6742461b057cf73698cda21de4dd24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
